### ISSUE TITLE
View not Found 

### ISSUE THREAD

**Issue by WeeSee** [thyseus/yii2-message#10]
I am using Yii2-user and now have installed Yii2-messages.

When I first try to send a message, there is an error ```View not Found``` and
```The view file does not exist: /var/<path-to-my-project>/mail/message.php```.

Obviously the search path for views does not contain ```vendors``` path first but looks in my projekt instead.

What's going wrong here?

**Comment by thyseus** [comment]
Did you set a theme? http://www.yiiframework.com/doc-2.0/guide-output-theming.html#theming-modules

**Comment by thyseus** [comment]
Also, could you check your mail view configuration?
http://www.yiiframework.com/doc-2.0/guide-tutorial-mailing.html#composing-mail-content

This is the line that could cause the headache: 
https://github.com/thyseus/yii2-message/blob/master/models/Message.php#L164

**Comment by WeeSee** [comment]
Hey superfast response, thanks!
I removed theming und it works now. 

Can I redefine the ```viewPath``` in the configuration with my application view path?

**Comment by thyseus** [comment]
You can always override all views and mails of every module like explained in the links above. It is an feature of the Yii Framework. You can contact me if you have questions on how to do this.
