### ISSUE TITLE
Send message from "system"

### ISSUE THREAD

**Issue by WeeSee** [thyseus/yii2-message#16]
What's a good way to send messages from an anonymous or administration account, e.g. for a new software version? There should be no way for the receiver to reply to this message.
In the compose-function, what value should "$from" get in this case?

**Comment by thyseus** [comment]
Hi and thanks for your interest in yii2-message !

You can set the $from parameter to null: 

https://github.com/thyseus/yii2-message/commit/7f5069ff690f677fc206cb7dd716c0b2a4677d94#diff-4ec234047be5a867b1cff28d59fc6109R34

The string defined in:

https://github.com/thyseus/yii2-message/blob/master/Module.php#L95

will be used for the "system" user.

i just added a little bit of documentation to the code.
