### ISSUE TITLE
Any plan to release 0.4.0?

### ISSUE THREAD

**Issue by bobonov** [thyseus/yii2-message#18]
I need 2 of the feature to be in 0.4.0
ENH: Allow to send messages without sender (messages coming from "the system")
ENH: Allow to use yii2-queue (https://github.com/yiisoft/yii2-queue)
so I'm looking forward for it.

**Comment by thyseus** [comment]
Hey - good to know !

you can use dev-master where this features are already implemented. Now that i know that people are using this, i am going to tag the 0.4.0 version soon. :)
