### ISSUE TITLE
bug in Messagecontroller->actionCheckForNewMessages()

### ISSUE THREAD

**Issue by bobonov** [thyseus/yii2-message#19]
At line 107 there is an if as follow
```php
            if ($count != $session->get($last) || $time_bygone) {
                return $count;
                Yii::$app->session->set($last, $count);

            }
```
The session set won't happen since is after a return

**Comment by thyseus** [comment]
Thanks a lot ! Fixed: https://github.com/thyseus/yii2-message/commit/0f7b188a0c066e61ee05b63674e52598f992943a
