### ISSUE TITLE
Setting unknown property: thyseus\message\Module::modelClass

### ISSUE THREAD

**Issue by gajen0981** [thyseus/yii2-message#2]
Getting a error when when user navigate to inbox route -  frontend/web/message/message/inbox
I am using Dektrium user module where I have extended their user model to add custom field so the the user class is in frontend\models\User. 
       
// Messaging
        'message' => [
            'class' => 'thyseus\message\Module',
            'modelClass' => 'frontend\models\User', // optional. your User model. Needs to be ActiveRecord.
        ],

**Comment by gajen0981** [comment]
Found the error with the config and how the user model class is referenced by this library "userModelClass" and not "modelClass". So the following works. 

![image](https://cloud.githubusercontent.com/assets/980887/24956026/d38cae40-1f53-11e7-83b8-af554c4fe58a.png)

**Comment by thyseus** [comment]
Hey, was just about to answer you. Glad you found the problem already.

In the future i want to make the message system to be working also without ActiveRecord. Goal will be that the module can be used with the yii2-basic-app. The work shouldn´t be too much but i can not promise a time for this at the moment. 

Enjoy the module :)

**Comment by thyseus** [comment]
Also see https://github.com/thyseus/yii2-message/issues/3

**Comment by gajen0981** [comment]
Thank you for the awesome work!!
